import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Calendar;

import javax.swing.JOptionPane;

/**
 *
 * @author Alberto
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form InterfazInicio
     */
	
	int puntuacion;
	
    public MenuFrame(int puntos) {
        initComponents();
        this.puntuacion = puntos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        guardarPartida = new javax.swing.JButton();
        nuevaPartida = new javax.swing.JButton();
        terminarJuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Seleccione una opcion: ");

        guardarPartida.setText("Guardar puntuacion");
        guardarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarPartidaActionPerformed(evt);
            }
        });

        nuevaPartida.setText("Nueva partida");
        nuevaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaPartidaActionPerformed(evt);
            }
        });

        terminarJuego.setText("Terminar juego");
        terminarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarJuegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(guardarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(nuevaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(terminarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(guardarPartida)
                .addGap(17, 17, 17)
                .addComponent(nuevaPartida)
                .addGap(17, 17, 17)
                .addComponent(terminarJuego))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarPartidaActionPerformed(java.awt.event.ActionEvent evt) {
        String nombre = JOptionPane.showInputDialog("Introduce tu nombre");
        try {
        	
        	SimpleDateFormat format = new SimpleDateFormat("d/M/y");
        	String fecha = format.format(Calendar.getInstance().getTime());
        	
        	Calendar reloj = Calendar.getInstance();
        	int min = reloj.get(Calendar.MINUTE);
        	int h = reloj.get(Calendar.HOUR_OF_DAY);
        	String hora = h +":"+ min;
        			
        	
        	String mensaje = "***************************\n"+
			                  "   ["+ fecha + " " + hora +"]\n"+
			                  "Jugador: "+ nombre + "\n"+
			                  "Puntuacion: "+ this.puntuacion + "\n"+
			                  "***************************\n\n";
        	
        	PrintWriter pw = new PrintWriter(new BufferedWriter(new FileWriter("./src/puntuaciones.txt", true)));
        	pw.write(mensaje);
        	pw.close();
        	
        	guardarPartida.setEnabled(false);
        } //Si existe un problema al escribir cae aqui
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"ERROR: Algo salio mal, vuelva a seleccionar la misma opcion.");
        }
    	
    }//GEN-LAST:event_guardarPartidaActionPerformed

    private void nuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {
        InterfazFrame nueva = new InterfazFrame();
        this.setVisible(false);
        nueva.setVisible(true);
    	
    }//GEN-LAST:event_nuevaPartidaActionPerformed

    private void terminarJuegoActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
    	
    }//GEN-LAST:event_terminarJuegoActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guardarPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nuevaPartida;
    private javax.swing.JButton terminarJuego;
    // End of variables declaration//GEN-END:variables
}
